### ISSUE TITLE
This plugin is Not working

### ISSUE THREAD

**Issue by ruhul080** [strangerstudios/pmpro-pay-by-check#1]
Hi,

I am using this plugin to manually activate the level after getting the check but it seems it is activating automatically during checkout by user. Is the plugin really works?

Thanks
Ruhul Amin

**Comment by 7starsone** [comment]
yes, same issue... first time the user completes the checkout can enter and even write an article :-D

**Comment by 7starsone** [comment]
I'm on Wordpress 4.2.2 ... in the meanwhile they try to fix, you have to wait for the confirmation email (where there's "***They have chosen to pay by check***") and you're forced to change the role of the user to Subscriber...in order to prevent him to write anything...

**Comment by thefill** [comment]
Howdy @7starsone, I can confirm issue. Looks like hook "pmpro_check_status_after_checkout" never fires ;-/ Below small hack / fix - place this snippet in your theme file. "Pay by Check" should work like charm ;-)
 
    /*
        Fix for no status change when using check gateway
    */
    function order_status_modification($order)
    {
        if($order->gateway == "check") {
            $order->status = 'pending';
            $order->sqlQuery = str_replace('success','pending',$order->sqlQuery);
        }

        return $order;
    }
    add_filter('pmpro_add_order', 'order_status_modification', 20);

Hope this will help!

**Comment by emiliano1991** [comment]
i use Paid membership pro plugin in my site. i use pay by check addon to allow the user to pay with bank transfer. when a user get a register the status is automatically set to “pending”; when pay I change the status on “success” to allow the user to access in your restricted content; but the user don’t receive an email to advice the change of status....

the smtp email in setting correctly. All email arrives correctly, only this not works.

why ? 

thanks

**Comment by 7starsone** [comment]
@thefill 
where I need to put that code?
Pasted in the them functions...but the user is always as "author" and can write...
