### ISSUE TITLE
Checkout button not swapping out

### ISSUE THREAD

**Issue by kgnbuchanan** [strangerstudios/pmpro-pay-by-check#15]
This plugin is perfect for what I'm trying to do, but when I choose the radio option to "Pay by Check", the checkout button is still the "PayPal Express" button. I see that this bug was fixed in version .3, but the error still seems to be occurring for me, do you have any suggestions?

**Comment by aquiferweb** [comment]
Same here:
in pmpro-pay-by-check.js
Cheque instructions are correctly displayed by .show() on line 74, but then the buttons are not swapped if the cheque gateway is selected.

**Comment by ctluciani** [comment]
I am also having this problem.

**Comment by breescorner** [comment]
It doesn't work for me either... the submit button is gone

**Comment by JarrydLong** [comment]
Just making a note here that this has been tested in version 0.11 and can confirm that the buttons change as expected.
