### ISSUE TITLE
pending user can see content hidden by shortcodes

### ISSUE THREAD

**Issue by esperanzo2008** [strangerstudios/pmpro-pay-by-check#16]
Pending users can see content hidden by [membership] Shortcode
Other restrictions work fine

**Comment by DarkLotus** [comment]
Hey you can solve this by adding a filter for pmpro_has_membership_level
```//Fix to block pending users from viewing any access
function gw_pmpro_has_membership_level($hasaccess, $user_id, $levels)
{
    //if they don't have access, ignore this
    if(!$hasaccess)
        return $hasaccess;
 
    $hasaccess = ! pmpropbc_isMemberPending($user_id);
    return $hasaccess;
}
add_filter("pmpro_has_membership_level", "gw_pmpro_has_membership_level", 10, 3);```

**Comment by andrewlimaza** [comment]
Making a note here, this code solution does help but it can affect other areas of Pay By Check. This would cause minor text display issues on restricted content or other Add Ons that may look for "pmpro_hasMembershipLevel".

It's a goof workaround for block access for PMPro - I'm busy working on a shortcode solution that should be released soon.

**Comment by andrewlimaza** [comment]
Here's the commit that fixes the shortcode accessible issue - https://github.com/strangerstudios/pmpro-pay-by-check/commit/60d51516cd0674e655ba8fa9897126df85f2e4f1
