### ISSUE TITLE
not send email order status “success” in membership-->orders paid membership pro

### ISSUE THREAD

**Issue by emiliano1991** [strangerstudios/pmpro-pay-by-check#2]
i use Paid membership pro plugin in my site. i use pay by check addon to allow the user to pay with bank transfer. when a user get a register the status is automatically set to “pending”; when pay I change the status on “success” to allow the user to access in your restricted content; but the user don’t receive an email to advice the change of status....

the smtp email in setting correctly. All email arrives correctly, only this not works.

why ?

thanks

**Comment by naftalent** [comment]
Hello, i have the same issues. Have you solved the problem?

**Comment by naftalent** [comment]
Hi @strangerstudios, any updates for us?

**Comment by primadesu** [comment]
I have same issues.
Please fix it.
Thanks Strangger Studio for your great plugin.

**Comment by primadesu** [comment]
Hi **@strangerstudios**, i have same isues. How to fix it?

**Comment by naftalent** [comment]
@primadesu hi, do you found how to solve this?

**Comment by cremigerhonig** [comment]
@strangerstudios still no fix for this? it´s been 8 years now nobody cared to even answer?

**Comment by ideadude** [comment]
There is no code in this plugin now to send an email when an admin changes the status of an order to success. It's expected that the person who manually makes that change can manually send an email.

If you'd like to open a new ticket for this as a feature request, include information about how you imagine it would work and also possibly how you might go about programming it. Then we can decide if we will take on that work or give guidance for a third party to code it. Closing this ticket for now.
