### ISSUE TITLE
Make compatible with Multiple Memberships per User

### ISSUE THREAD

**Issue by strangerstudios** [strangerstudios/pmpro-pay-by-check#22]
If a user has more than one level, they might have access to a post via one level but still be pending for another level. In this case, we want to give them access to the post.

We would need to update this line to loop through all levels:
https://github.com/strangerstudios/pmpro-pay-by-check/blob/master/pmpro-pay-by-check.php#L475

If the user has any of those levels and is ! pending, then give them access. Otherwise don't.

The pending function needs to be updated to do something with the level_id passed in.

**Comment by strangerstudios** [comment]
Should we also filter pmpro_has_membership_level to return false if a user is pending. If so, we can just check if pmpro_hasMembershipLevel for all of the levels the post is locked down for and return true if the user has any of them.

**Comment by strangerstudios** [comment]
Here is how the approvals plugin filters pmpro_hasMembershipLevel https://github.com/strangerstudios/pmpro-approvals/blob/master/pmpro-approvals.php#L407

**Comment by kimcoleman** [comment]
This is resolved in v1.0 https://github.com/strangerstudios/pmpro-pay-by-check/releases/tag/1.0
