### ISSUE TITLE
Problem in case "check not received"

### ISSUE THREAD

**Issue by cdgdigital** [strangerstudios/pmpro-pay-by-check#24]
When a new member puts an order with "pay by check":
- he receives a welcome email with a "pending" status;
- order/invoice is set to "pending"
- but sales report does compute order's value as sold.

If the member never sends the check, deposit or bank transfer, I should only have to CANCEL the order/invoice and, automatically, sales value should be removed from sales report, and membership should be cancelled.

However, currently, even when I cancel the order/invoice, sales value continues to show up on sales report and membership still shows on reports as "pending" instead of "cancelled".

One suggestion to correct this type of problem is to create two documents: (i) ORDER and (ii) INVOICE.  So, when there is a new membership request, an ORDER is placed by prospect member, and it waits to be fulfilled and paid; SALES is not yet increased or, if increased, RECEIVABLES should also be increased.  Only after ORDER request is approved, fulfilled and paid is that the INVOICE is generated and sent, membership level is applied, access is permitted, and SALES is increased or RECEIVABLES decreased.

SUMMARY: Create ORDER and INVOICE as separated documents, and SALES and RECEIVABLES as separated reports/accounts.

**Comment by MaryOJob** [comment]
The same issue was reported by another user. In my case, it shows as Paid. I created a bug report here: 
Moderators Only: #407815

**Comment by kimcoleman** [comment]
We removed "cancelled" as an order status in v3.0. This is not a valid status for an unpaid order.
