### ISSUE TITLE
BUG: When used in conjunction with PMPro Auto Renew settings are sometimes not saved correctly

### ISSUE THREAD

**Issue by greathmaster** [strangerstudios/pmpro-pay-by-check#33]
To reproduce…

1) install and activate Paid Memberships Pro, PMPro Pay by Check, and PMPro Auto Renew
2) click Add Level
3) for the PMPro Pay by Check option "Allow Pay by Check" choose "Yes. Users choose between the default gateway and check"

4) for the PMPro Auto Renew option "Auto-Renewal Optional?" choose "Yes. Default to checked"
5) under "Content Settings" click checkbox of any category
6) save the level
7) return to the level settings
8) the settings have now changed to "No. Use the default gateway only" for the PMPro Pay by Check  Add On settings and  "No. All checkouts will setup recurring billing." for the PMPro auto renew Add On settings.

**Comment by kimcoleman** [comment]
We are not hearing current reports of this issue. Closing until we can see if this is resurfacing with the latest releases.
