### ISSUE TITLE
Bug: Loading checkout page JS on any request where $post is not set.

### ISSUE THREAD

**Issue by messica** [strangerstudios/pmpro-pay-by-check#34]
pmpro-pay-by-check.js is loaded on any front end request when $post is not set, including category archives, etc.

https://github.com/strangerstudios/pmpro-pay-by-check/blob/4c3a4d08e96bfe79bea890d327fc77813a3d7ff2/pmpro-pay-by-check.php#L224-L226

**Support Ticket (Moderators Only)**
https://www.paidmembershipspro.com/forums/topic/pay-by-check-disappear/

**Comment by kimcoleman** [comment]
This PR may be the correct fix: https://github.com/strangerstudios/pmpro-pay-by-check/pull/28/files

**Comment by ideadude** [comment]
Merged in that PR
