### ISSUE TITLE
Enhancement: Recurring orders SQL filter (for use with Add Ons like Subscription Delays)

### ISSUE THREAD

**Issue by messica** [strangerstudios/pmpro-pay-by-check#35]
The Pay by Check Add On is not compatible with the Subscription Delays Add On because the pmpro_profile_start_date filter isn't used for check gateways. We could solve this by adding a filter at https://github.com/strangerstudios/pmpro-pay-by-check/blob/596a35da21de85df3d9d22adf63a192b42c73db6/pmpro-pay-by-check.php#L656 to modify the SQL query used to find recurring orders though.

**Support Ticket(Moderators Only)**
https://www.paidmembershipspro.com/forums/topic/member-renewals-for-association/

**Comment by kimcoleman** [comment]
We are not hearing current reports of this issue. Closing until we can see if this is resurfacing with the latest releases.
