### ISSUE TITLE
Bug: Billing page displays primary gateway's settings.

### ISSUE THREAD

**Issue by messica** [strangerstudios/pmpro-pay-by-check#36]
When a user pays by check, the Billing page still shows the primary gateway's settings.

**Support Ticket (Moderators Only)**
https://www.paidmembershipspro.com/forums/topic/recurring-paid-by-check-shows-paypal-message/

**Comment by kimcoleman** [comment]
This should be resolved in the current release. Closing until we can see if this is resurfacing with the latest releases.
