### ISSUE TITLE
Non-numeric Value Warning.

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/pmpro-pay-by-check#41]
A user has reported they are getting the following error:

> A non-numeric value encountered in /home/dir/public_html/wp-content/plugins/pmpro-pay-by-check/pmpro-pay-by-check.php on line 449

PHP: 7.3.6

**Moderators Link**
https://www.paidmembershipspro.com/forums/topic/php-warning-about-pay-by-check/

**Comment by jcimb** [comment]
in PHP 7.1, an E_WARNING is emitted when the string does not contain a numeric value.

**Comment by andrewlimaza** [comment]
Hi @jcimb do you receive an error on the exact same line? Please feel free to share your error message here (and scrub out any private information like file path names/directory names etc)

**Comment by jcimb** [comment]
Yes, all are on the same line:
[07-Oct-2020 17:01:40 UTC] PHP Warning: A non-numeric value encountered in /home/xxxxxxxx/public_html/wp-content/plugins/pmpro-pay-by-check/pmpro-pay-by-check.php on line 473

**Comment by jcimb** [comment]
Hi, just checking on the status. Still getting the warning, multiple ones daily.

**Comment by jcimb** [comment]
`} else {
					$cutoff = strtotime("- " . $membership_level->expiration_number . " " . $membership_level->expiration_period, current_time("timestamp")) - ($options['cancel_days']*3600*24);
				}`

**Comment by kimcoleman** [comment]
We are not hearing current reports of this issue. Closing until we can see if this is resurfacing with the latest releases.
