### ISSUE TITLE
When order is cancelled, invoice page shows "Paid"

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/pmpro-pay-by-check#57]
There seems to be an issue with the order status on the frontend Invoice page.

Steps to recreate:

1. Checkout for a level that uses the Pay By Check Add On/payment gateway.
2. Cancel the order status via the admin screen.
3. Navigate to the frontend invoice page for this specific order, the order status shows "Paid".

This status also shows as "Paid" on the members account page.

**Comment by andrewlimaza** [comment]
PS - tested this for orders that belong to other gateways. The same issue occurs.

**Comment by kimwhite** [comment]
changing Pending to Canceled also gives user full access to the site.

**Comment by andrewlimaza** [comment]
This came up recently, and it's designed this way in core. As pending status for other (automatic) gateways like Stripe/PayPal etc means that money is paid so it shows "Paid".

Pay By Check treats "Pending" status differently, as money not received. We will need to tweak some logic here that all statuses except "Success" with Pay by Check should restrict access.

**Comment by kimcoleman** [comment]
We removed "cancelled" as an order status in v3.0. This is not a valid status for an unpaid order.
