### ISSUE TITLE
Emails not being sent

### ISSUE THREAD

**Issue by kimwhite** [strangerstudios/pmpro-pay-by-check#59]
I created a user with recurring check payments.  Setup Send Renewal Emails waited for that date, manually ran cron.
A new invoice was created (can see on the Members-Account page) but no email was sent.

An email was sent at registration, then when the first check was received and the order was marked success.
But no EMAIL when the new Invoice was created.

**Comment by cremigerhonig** [comment]
On my end there is no mail send at all, just once after registration. No email if order was marked as success.
Why?

**Comment by andrewlimaza** [comment]
Closing this as it's a duplicate issue.
