### ISSUE TITLE
How to translate Payment Method?

### ISSUE THREAD

**Issue by ghost** [strangerstudios/pmpro-pay-by-check#6]
Hy.**@strangerstudios** how to translate payment method "Pay by Check"
I was following your guide 

>  you would like to change the wording from "Pay by Check" to something else, you can use this custom code:
> https://gist.github.com/strangerstudios/68bb75bf3b83530390d4

but not work.
I'm looking at LOCO translate and PO edit but nothing to change.
Here is the screen shot
![translate this](https://cloud.githubusercontent.com/assets/18297995/14303625/808f4430-fbde-11e5-9b43-4391c8456cdc.png)

ScreenShot URL:
http://--your-domain-pmp.com/membership-account/membership-invoice/?invoice=26C21BFF8A

**Comment by accessallareas** [comment]
Same problem here. Added a German translation but results won't show.

**Comment by cremigerhonig** [comment]
I was searching for hours and couldn´t fix it. same problem here, any ideas? how to solve it?

**Comment by cremigerhonig** [comment]
solved it 

wp-content/plugins/paid-memberships-pro/classes/gateways/class.pmprogateway_check.php:165
