### ISSUE TITLE
BUG: Invoice email being sent every time check order is saved in "success" status

### ISSUE THREAD

**Issue by dparker1005** [strangerstudios/pmpro-pay-by-check#61]
To replicate, create a "Check" order in "Success" status and save it repeatedly. The user associated with the order will receive an Invoice email every time that the order is saved.

This should be addressed in the `pmpropbc_send_invoice_email()` function here:
https://github.com/strangerstudios/pmpro-pay-by-check/blob/6ae07a846434d5582f89661fc50b63ce63dae330/pmpro-pay-by-check.php#L590-L607

Suggested fix is to save in order meta when an invoice email has already been sent for a given order, and if that is the case, to not allow another invoice email to be sent.

**Comment by cremigerhonig** [comment]
for me no mail is send at all

if I change from pending to sucess there is no mail sent to user, why?
