### ISSUE TITLE
Users gain immediate access even if -status pending-

### ISSUE THREAD

**Issue by cremigerhonig** [strangerstudios/pmpro-pay-by-check#64]
Using PMPro with Pay by check 

unfortunately new users gain immediate access to content that is blocked by shortcode immediately after registration (pay by check) even if status is marked as pending

**Comment by ideadude** [comment]
Related issue with work around: https://github.com/strangerstudios/pmpro-pay-by-check/issues/16

**Comment by cremigerhonig** [comment]
`/** 	pending user can see content hidden content by shortcodes
	*/	
	
function gw_pmpro_has_membership_level($hasaccess, $user_id, $levels)
{
    //if they don't have access, ignore this
    if(!$hasaccess)
        return $hasaccess;
 
    $hasaccess = ! pmpropbc_isMemberPending($user_id);
    return $hasaccess;
}
add_filter("pmpro_has_membership_level", "gw_pmpro_has_membership_level", 10, 3);	`
