### ISSUE TITLE
pmpro / pay by check doesn´t send email if order status change from pending to success

### ISSUE THREAD

**Issue by cremigerhonig** [strangerstudios/pmpro-pay-by-check#65]
Still open issue, nobody cares?

Bug is 8 years old:
https://github.com/strangerstudios/pmpro-pay-by-check/issues/2

Also new orders are not created automatically if subscription is recurring, and NO email is send too

**Comment by ideadude** [comment]
I closed #2 with a message if you want to reopen it.

RE the recurring orders. It should send an email about the pending order.

https://github.com/strangerstudios/pmpro-pay-by-check/blob/dev/pmpro-pay-by-check.php#L727-L734

We can try to recreate this on our environment. Any information you might have on how or why this is happening would help.

**Comment by ideadude** [comment]
While we look into the recurring order issue, you will want to check that your cron jobs are running. You can use the WP Crontrol plugin.

https://wordpress.org/plugins/wp-crontrol/

Here's where we schedule the crons: https://github.com/strangerstudios/pmpro-pay-by-check/blob/dev/pmpro-pay-by-check.php#L1012-L1014

There is one called pmpropbc_recurring_orders, but a couple others as well.

If you don't see those via WP Control, then you can try deactivating and reactivating the Pay by Check plugin to try to get them recreated again.

If you do see them, you can try to "run it once" and see if the orders are created then. If that's the case, then there is a problem with your WP Cron triggering. Some info here on troubleshooting cron jobs:

https://www.paidmembershipspro.com/troubleshooting-issues-with-wp-cron-and-other-scheduled-services/

**Comment by cremigerhonig** [comment]
Thanks for your fast reply. 
After registration and checkout with the "pay by check" plugin (using Version: 0.9) an email (send email template: "checkout - check") is send to the user

afterwards an admin change the order status from pending to success and nothing happens. The user doesn´t get any email notification about the new status of his payment. He doesn´t know about his access?!

Also, I saw your message on https://github.com/strangerstudios/pmpro-pay-by-check/issues/2 and I think it´s not a good idea to "...expect that the person who manually makes that change can manually send an email..." this kind of logic makes things even worse and increase the workload dramatically. 
Why isn´t this totally obvious and basic feature not there already in there out of the box? 

Furthermore the (NEW) User is able to see restricted content (restricted by shortcode) right away even if the status of the order is still pending.

also see here:
https://github.com/strangerstudios/pmpro-pay-by-check/issues/64

**Comment by ideadude** [comment]
Noted

**Comment by cremigerhonig** [comment]
https://github.com/strangerstudios/pmpro-pay-by-check/issues/1#issuecomment-135974363

After registration and checkout with the "pay by check" plugin (using Version: 0.9) an email (send email template: "checkout - check") is send to the user

afterwards an admin change the order status from pending to success and nothing happens. The user doesn´t get any email notification about the new status of his payment. He doesn´t know about his access?!

**Comment by andrewlimaza** [comment]
I know this is an old issue, and has been resolved for a while but I thought to leave some feedback.

This has been updated to send the Invoice Email that PMPro provides when changing to success status (this is done only once). Just updating this issue, please use the latest version.

You can tweak the email or copy the logic and send a custom email.

https://github.com/strangerstudios/pmpro-pay-by-check/blob/dev/pmpro-pay-by-check.php#L767-L795
