### ISSUE TITLE
One-time payment memberships may be considered recurring

### ISSUE THREAD

**Issue by dparker1005** [strangerstudios/pmpro-pay-by-check#69]
PMPro Pay by Check has logic designed specifically for recurring levels to:
1. Create an order in `pending` status x days before a payment is due
2. Send a reminder email for orders still in `pending` status y days after a payment is due
3. Cancel memberships for orders still in `pending` status z days after a payment is due

This behavior is meant to only affect recurring memberships, but consider a site with the Auto-Renewal Checkbox Add On where the same membership level can be recurring for some users and be a one-time payment for others. On this kind of site, we would expect recurring memberships to follow the steps above, and one-time payment memberships to ignore them all.

In the code, we try to figure out whether a membership level is recurring by looking to see if there are `active` memberships with a non-zero cycle number:
`$sqlQuery = "SELECT DISTINCT(CONCAT(cycle_number, ' ', cycle_period)) FROM $wpdb->pmpro_memberships_users WHERE membership_id = '" . $level->id . "' AND cycle_number > 0 AND status = 'active'";`
If such a record is found, we then get all orders for that membeship level and treat them as recurring orders.

The issue here is that this includes memberships which are actually one-time payment memberships just because they have the same level ID. We are handling this case correctly in the `pmpropbc_recurring_orders()` function by using the following code while looping through orders/memberhsips:
`if( $user->membership_level->cycle_number == 0 || $user->membership_level->billing_amount == 0)
				  continue;
`
The `pmpropbc_reminder_emails()` and `pmpropbc_cancel_overdue_orders()` functions do not, however, have this check.

Here is a case where this may cause an issue:
1. Auto-Renewal Checbox Add On is active w/ "Cancel Membership" setting set to `0`
2. There are active recurring memberships
3. User checks out deciding not to auto-renew
4. In this case, the user's membership will be cancelled the next day since the membership will be treated as recurring due to the other recurring memberships on the site.
5. Note that this will also leave the order in `pending` status, which is confusing

**Comment by andrewlimaza** [comment]
Nice catch on this one, I've added a PR that adds these checks which should resolve these issues (and possibly other issues similar to this).
