### ISSUE TITLE
Restricts content for non-members set with membership shortcode

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/pmpro-pay-by-check#71]
**Describe the bug**
When content is set for non-members using the membership shortcode, e.g. `[membership level="0"]Display for non-members[/membership]` the [pmpropbc_pmpro_member_shortcode_access](https://github.com/strangerstudios/pmpro-pay-by-check/blob/374702488de17ee1ed719287b716614e3953abf7/pmpro-pay-by-check.php#L529-L540) function removes access for non-members due to a [check for active membership levels for the current user](https://github.com/strangerstudios/pmpro-pay-by-check/blob/374702488de17ee1ed719287b716614e3953abf7/pmpro-pay-by-check.php#L536).

**To Reproduce**
1. Go to Pages > Add New and create a new page containing the shortcode `[membership level="0"]Display for non-members [/membership]` and publish the page.
2. In a new private/incognito browser navigate to this page as a non-logged-in visitor
3. See error

**Expected behavior**
The content inside the membership shortcode should be filtered according to the level parameter

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by michaelbeil** [comment]
As reported in ticket 433246 (moderators only).
> When we have the pay by check plugin activated, the custom membership levels page shows blank for expired or new members. Only members with an active level can see the custom membership levels again. I currently have the pay by check deactivated but do still have the fix in our customizations plugin, it just isn’t working any longer.
I sent them the PR.
