### ISSUE TITLE
Changing cost of level based on payment type

### ISSUE THREAD

**Issue by bethgee** [strangerstudios/pmpro-pay-by-check#93]
Is there any way to customise this add on to change the price depending on which payment type is chosen?? My client wants to charge the customer the extra % from Stripe or allow them to pay by Bank Transfer without the additional charge.

However, I cannot see a way to do this on a single checkout page per level.... Any ideas??

**Comment by andrewlimaza** [comment]
Hi @bethgee 

Thanks for reaching out, we don't often look at Github for support requests. For support, please reach out on www.paidmembershipspro.com/support

To help get you started, you may use this guide as a starting point - https://www.paidmembershipspro.com/modify-level-price-at-checkout-based-on-user-selections/ as this solution will require some custom code at this point to achieve.

I hope this helps get you started.

**Comment by kimcoleman** [comment]
This is possible with the Payment Plans Add On: https://www.paidmembershipspro.com/add-ons/pmpro-payment-plans/
